""" 
Duplas
Una tupla es una colección ordenada pero inmutable, lo que significa que no
se puede modificar los elementos una ves definidos.

Caracteristicas:
 Son ordenadas
 Son inmutables
 Pueden contener elementos duplicados
 los elementos puede ser diferentes tipo datos
"""

mi_tupla = (10,20,30,40,"Hola")
print(mi_tupla[2])

#intenta cambiar elemento
#mi_tupla[1 = 40 #esto genera error] Type Error

print(len(mi_tupla))