# == IGUAL A

a = int(input("Ingresa el primer número: "))
b = int(input("Ingresa el segundo número: "))
if a == b:
    print("a es igual a b")
else:
    print("a y b son diferentes")

#distitntos de (!=)

if a != b:
    print("a y b son diferentes")
else:
    print("a y b son iguales")

#mayor que (>)
if a == b:
    print("a y b son iguales")
if a > b:
    print("a es mayor que b")
else:
    print("a no es mayor que b")